language: ruby
rvm:
- 2.4.1
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: Sora233
  - EMAIL: sora@sora233.me
  - secure: gsUtOHy3doyyufuJJ3msvmNP1k2RaKDi51zoJwoQlCmCLkJjWfYgjG/uMWeLSmHsPc4D9yrNen0qXHDVtcOwRwvVOnj6IFMXersj+VOvhtuYY/KW2c2FrnB8H4O1UF6U99B5KXl3I/VSKbKi55XPawmzSF7zwFr0xtADVJztkEFnSfC03ogtKNgcniytNqJ4vmEyCbv8zpf9ff9NFPJuVgJJ+INSCdmtmX0CvMciEB76X/MsFagq5qv2o1rLgguSb7Nr8IoRxZLKQJvYsgeKi+KYAlR7BkxZzv0FDfFLE48763uRMFc6DluQmirW767LyCA34wrte3CCPtO7KgBKW4Hh+bJ4ZVVyTm6tnm51ygEckUo3snKEYIZOcHw4LhzTj7K1O1mKqcb6PkBP9kC6XBMgrOO2LvWdhHedvHmmqXB8z4o3lELGfmtZUf5hipLN8cvn5eysU9KqkSnDDMeVDovafDAdX23i67ofOGplqsqFbTdLXw87548zDA7Ra4a7OfR+IUkTIcPbVZXL+lrSswDPpnhd35P5MLxcMsE8sJOXVBjH7sBdRfBw1I5tehk1lmzP4TzACU+H4qTAS3iLneqt3YLd4ARk0VAwAzgSApvjiw7VPD6lX4AeAveD9DC0WrxJptTYmvttLB1VaAMpcQDbp+20XnlYM43yGLQqBpU=
